# Test playbook
---
- hosts: all
  become: true
  vars:
    NS: TRAVIS
  roles:
    - role: users
    - role: repo
      openio_repository_no_log: false
      openio_repository_products:
        sds:
          release: "18.04"
    - role: gridinit
      openio_gridinit_namespace: "{{ NS }}"
      openio_gridinit_per_ns: true
    - role: redis
      openio_redis_namespace: "{{ NS }}"
    - role: role_under_test
      openio_account_namespace: "{{ NS }}"
      openio_account_redis_standalone: "{{ ansible_default_ipv4.address }}:6011"
...
